[paths]
attachments = "attachments"
templates   = "templates"
leads       = "leads"

[defaults]
delay_seconds   = 2.5
sheet_name      = "Sheet1"
timezone        = "Europe/Zurich"
default_leads_file = "LL_Ready.xlsx"
template_base   = "Mukran_template_notion_export"
account         = ""
template_column = "template"
language_column = "language"
cc_column       = "cc"
cc_threshold   = 3
subject_line    = "Default Subject Settings"